
#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'mlastronomy'
version: '0.14.0'
config-version: 2
profile: mlastronomy
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
test-paths: ["test"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  'run_time': 'RUN_TIME'
  'actuals_variables': ['DATE','PRODUCT']
  'predictions_variables': ['DATE','PRODUCT']
  'regression_models': ['regression_staging','regression_2_staging']

models:
  mlastronomy:
    base:
      +materialized: ephemeral
